export const TRAFFIC_LIGHT_INSET = 16;
const TRAFFIC_LIGHT_CLUSTER_WIDTH = 52;
const TRAFFIC_LIGHT_GUTTER = -8;

export const MAC_CONTENT_INSET =
  TRAFFIC_LIGHT_INSET + TRAFFIC_LIGHT_CLUSTER_WIDTH + TRAFFIC_LIGHT_GUTTER;
